AWSTemplateFormatVersion: 2010-09-09
# IAM Roles to include:
# AWSCodePipelineServiceRole-us-west-1-Development-web-app-CF-pip
# codebuild-Development-CF-Bundle-Build-service-role
# codebuild-Development-EB-AppVersion-Build-service-role
# CreateRoleForCodePipeline-CFNRole-U9792FMMZ54Y

# IAM Policy
Version: 2012-10-17
Statement:
  - Sid: VisualEditor0
    Effect: Allow
    Action:
      - 'logs:DescribeLogGroups'
      - 'logs:CreateLogGroup'
      - 'logs:DeleteLogGroup'
      - 'logs:PutSubscriptionFilter'
      - 'logs:PutRetentionPolicy'
      - 'logs:DeleteSubscriptionFilter'
      - 'ecr:GetAuthorizationToken'
    Resource: '*'
  - Effect: Allow
    Action:
      - 's3:*'
    Resource:
      - 'arn:aws:s3:::elasticbeanstalk-*'
      - 'arn:aws:s3:::elasticbeanstalk-*/*'
      - 'arn:aws:s3:::codepipeline-*'
      - 'arn:aws:s3:::codepipeline-*/*'
      - 'arn:aws:s3:::development-datalake-artifact'
      - 'arn:aws:s3:::development-datalake-artifact/*'
  - Sid: ElasticBeanstalkReadOnlyAccess
    Effect: Allow
    Action:
      - 'rds:Describe*'
      - 'sqs:Get*'
      - 'sqs:List*'
    Resource: '*'
  - Sid: ElasticBeanstalkDeployAccess
    Effect: Allow
    Action:
      - 'autoscaling:*'
      - 'cloudformation:*'
      - 'ec2:*'
      - 'elasticloadbalancing:*'
      - 'elasticbeanstalk:*'
      - 'cloudwatch:*'
      - 'ecs:*'
      - 'application-autoscaling:*'
      - 'iam:*'
      - 'sns:*'
    Resource:
      - '*'

# IAM Role Trust Relationship
Version: 2012-10-17
Statement:
  - Effect: Allow
    Principal:
      Service: cloudformation.amazonaws.com
    Action: 'sts:AssumeRole'